name: CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox codecov pre-commit
      
      # Run tox using the version of Python in `PATH`
      - name: Run Tox
        env:
          AIRTABLE_KEY: ${{ secrets.AIRTABLE_KEY }}
        run: tox -e py
      
      # Run pre-commit
      # Disable for now
      # - name: run pre-commit
      #  run: pre-commit run --all-files
      
      - name: Upload Results
        if: success()
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          fail_ci_if_error: false

  deploy:
    needs: [tests]
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags')
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8" 
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16'
     
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[deploy]'
          npm install -g aws-cdk@1.158.0
          cdk acknowledge 19836
      
      - name: cdk deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'
          CDK_DEFAULT_REGION: 'us-east-2'
          CDK_DEFAULT_ACCOUNT: '4977-6086-9739'  
          AIRTABLE_KEY: ${{ secrets.AIRTABLE_KEY }}
          STAGE: prod
        run: cdk deploy rezoning-api-lambda-prod --require-approval never

  deploy-dev:
    needs: [tests]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/dev' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8" 
      - uses: actions/setup-node@v2-beta
        with:
          # 12 seems to hang. CDK 1.x seems to run with 16
          node-version: '16'
     
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[deploy]'
          # pin the CDK to the last v1 version
          npm install -g aws-cdk@1.158.0
          cdk acknowledge 19836

      - name: cdk deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'
          CDK_DEFAULT_REGION: 'us-east-2'
          CDK_DEFAULT_ACCOUNT: '4977-6086-9739'  
          AIRTABLE_KEY: ${{ secrets.AIRTABLE_KEY }}
          STAGE: dev
        run: cdk deploy rezoning-api-lambda-dev --require-approval never

